language: node_js
node_js:
  - "6"

# BLOCK LIST
branches:
  except:
    - master

# SAFE LIST 
branches:
  only:
    - angular
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build.prod

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: angular