language: node_js
node_js:
  - "6"

# BLOCK LIST
branches:
  except:
    - master

# SAFE LIST 
branches:
  only:
    - angular
 
cache:
  directories:
    - node_modules

#before_script:
#  - npm install -g firebase-tools
#  - npm install -g @angular/cli

script:
#  - npm run build.prod
  - ng build --prod

# uncomment to host in firebase
after_success:
  - firebase deploy --token $FIREBASE_TOKEN

# uncomment to host in github-pages
#deploy:
#  provider: pages
#  skip-cleanup: true
#  keep-history: true
#  github-token: $GITHUB_TOKEN
#  target-branch: master
#  local-dir: dist
#  on:
#    branch: angular