title: BrianTria.GitHub.IO
description: A collection of code snippets and mini projects<br/>(WebGL, Android, or Windows PC).

# Build settings
show_downloads: false
theme: jekyll-theme-midnight
permalink: /:categories/:title/

# Google Analytics Tracking ID 
# google_analytics:

# markdown: kramdown
highlighter: rouge
