title: BrianTria.GitHub.IO
description: A collection of code snippets and mini projects<br/>(WebGL, Android, or Windows PC).

show_downloads: false

# Google Analytics Tracking ID 
# google_analytics:

theme: jekyll-theme-midnight
# permalink: /:categories/:title/

# Main Pages
collections:
  main_pages:
    output: true
    permalink: /:name