title: "Portfolio: Brian Tria"
description: A collection of simple projects made with Unity.
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
highlighter: rouge
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock