title: Brian's Portfolio
description: A collection of code snippets and mini projects (WebGL, Android, or Windows PC).

show_downloads: false

# Google Analytics Tracking ID 
# google_analytics:

theme: jekyll-theme-midnight
permalink: /:categories/:title/